name: jou
on:
  push:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/set-cron-schedule-action@v2
        with:
          token: ${{ secretes.TOKEN }}
          cron: |
            */5 * * * *
          workflow: pa.yml
          message: "jou"
